version = 0.1
[default.deploy.parameters]
stack_name = "ws-serverless-patterns-orders"
resolve_s3 = true
s3_prefix = "ws-serverless-patterns-orders"
region = "us-east-2"
profile = "awsfreetier"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UserPool=\"us-east-2_OHQQb1Nid\""
image_repositories = []
